"use client"
import type { Metadata } from "next";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { WagmiProvider } from "wagmi";
import { config } from "./web3/config";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import 'nprogress/nprogress.css';
import { Sofia_Sans } from "next/font/google";
import { ReactNode, useEffect, useState } from "react";
import { isDarkMode } from "./utils/func";
import { MediaQueryContext, ThemeContext } from "./context/context";
const sophia = Sofia_Sans({ subsets: ["latin"] });
import { useMediaQuery } from 'react-responsive';

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function Provider({
  children,
}: { children: ReactNode }) {
  const queryClient = new QueryClient();
  const isMobile = useMediaQuery({ query: '(max-width: 768px)' });

  const [darkMode, setDarkMode] = useState(isDarkMode);
  useEffect(() => {
    if (darkMode) {
      document.documentElement.classList.add('dark')
    } else {
      document.documentElement.classList.remove('dark')
    }
  }, [darkMode])


  return <WagmiProvider config={config}>
    <QueryClientProvider client={queryClient}>
      <ToastContainer position="bottom-right" />
      <ThemeContext.Provider value={{ isDarkMode: darkMode, setDarkMode }}>
        <MediaQueryContext.Provider value={isMobile}>
          {children}
        </MediaQueryContext.Provider>
      </ThemeContext.Provider>
    </QueryClientProvider>
  </WagmiProvider>
}
