import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css"
import Footer from "@/app/components/footer";
import NewsLetter from "@/app/components/newsletter";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import TopBar from "@/app/components/landingtopbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <TopBar />
      {children}
      <Footer />
    </>
  );
}
